# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frontend.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66rontend.proto\"H\n\x10\x46\x32\x42\x43hangeAddress\x12\x0e\n\x06seqnum\x18\x01 \x02(\x03\x12\x0e\n\x06shipid\x18\x02 \x02(\x03\x12\t\n\x01x\x18\x03 \x02(\x05\x12\t\n\x01y\x18\x04 \x02(\x05\"F\n\x14\x42\x32\x46\x43hangeAddressResp\x12\x0e\n\x06seqnum\x18\x01 \x02(\x03\x12\x0e\n\x06shipid\x18\x02 \x02(\x03\x12\x0e\n\x06result\x18\x03 \x02(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frontend_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _F2BCHANGEADDRESS._serialized_start=18
  _F2BCHANGEADDRESS._serialized_end=90
  _B2FCHANGEADDRESSRESP._serialized_start=92
  _B2FCHANGEADDRESSRESP._serialized_end=162
# @@protoc_insertion_point(module_scope)
